### ISSUE TITLE
Search for block number doesn't work

### ISSUE THREAD

**Issue by metachris** [martriay/flashbots-explorer#35]
No matter which block number I enter, I get this error:

![Screenshot 2021-06-23 at 11 30 23](https://user-images.githubusercontent.com/116939/123073239-89ba7780-d416-11eb-9b2b-d6da20685bb1.png)

**Comment by martriay** [comment]
Hey @metachris, I wasn't able to reproduce this.

* Do you see any errors in the console?
* Can you provide a few block numbers to test it out?

**Comment by metachris** [comment]
It's not happening anymore! There were no errors in the console. 

🤷

**Comment by martriay** [comment]
Maybe there was a problem with the API? 🤷
